name: Push Container to Heroku

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '5.0.201' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    #- name: Install dependencies
    #  run: dotnet restore
    #- name: Dotnet Publish changes
    #  run: dotnet publish -c Release -o release
    - name: Install expect
      run:
        sudo apt-get update && sudo apt-get install expect
    - name: Set execute
      run: chmod 755 heroku-login.exp
    - name: Login to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        HEROKU_PASSWD: ${{ secrets.HEROKU_PASSWD }}
      run:
        expect -d heroku-login.exp ${{ secrets.HEROKU_PASSWD }}
    #- name: Set build pack
    #  run: heroku buildpacks:set https://github.com/heroku/heroku-buildpack-static -a dsp-statistics-panel
    - name: Deploy
      run: heroku static:deploy -a dsp-statistics-panel

